
# data path 
train_data_path: "NewDataset"
train_json_name: "data.json"
test_data_path: "TestWave"
test_json_name: "test.json"
image_path: "images"

# input testing file
test_file_name: "song.wav"

# model parameters
n_neighbors: 5 # number of neighbors in KNN algorithm
split_ratio: 0.25
random_seed: 20010113

# preprocessing parameters
mode: "test" # train / test
unit: 44100 # splitting unit for test file
